### ISSUE TITLE
翻訳とコードリーディング共同開催か決める

### ISSUE THREAD

**Issue by MSakamaki** [fxosorg/fxos-code-reading#15]
第１７回のときに、翻訳チームの人に総酸

**Comment by MSakamaki** [comment]
１８回はしない方向で

**Comment by aoitan** [comment]
共催しない経緯知りたい
今後共催考えるときに気にするべきこととかを把握しておきたいので

**Comment by MSakamaki** [comment]
@aoitan 
２７日に、@flatbird  さんとお話した感じ
翻訳は各月くらいでやりたいみたいな事を聞いたので。
やるとしたら１９回かなと。
