### ISSUE TITLE
開催概要 

### ISSUE THREAD

**Issue by aoitan** [fxosorg/fxos-code-reading#3]
告知サイトに書く開催概要考える
- [x] 初心者向け導入やるか > やる
  - 翻訳は mar さん[依頼済](https://twitter.com/flatbirdH/status/594073711700881408)。
  - コードリーディングはひらとりが準備。
- [x] おやつとかどうするか > やぶりんが買ってくれるらしい
- [x] 時間割どうするか > 下記コメント参照
- [x] 懇親会と懇親会費どうするか > やる。GCGさんご支援お願いします。
  - やるならとりあえずGCG勉強会支援つつきます
- [x] 人数 > 40人（各20で募集）

**Comment by flatbird** [comment]
#### 時間割

| 時間 | 内容 |
| --- | --- |
| 19:00-19:30 | 挨拶・合同自己紹介（全員） |
| 19:30-21:00 | わいわいコードリーディング・翻訳（初心者向け導入あり） |
| 21:00-22:00 | 懇親会＋ゆるゆる成果発表 |

※ 合同自己紹介は時間かかるかもなので、作業始められる人は始めてもらう。

**Comment by aoitan** [comment]
告知サイト記載済みなのでクローズ
